In [3]:
import pyodbc
import pandas as pd
from boxsdk import JWTAuth, Client
from datetime import datetime, timezone
import os
import logging
from logging.handlers import TimedRotatingFileHandler

conn_str = (
    r'Driver={ODBC Driver 17 for SQL Server};'
    r'Server=dca1-up-dls;'
    r'Database=IACOE;'
    r'Trusted_Connection=yes;'
    )

cnxn = pyodbc.connect(conn_str)

cursor = cnxn.cursor()

query = """SELECT * FROM TaxML_Validation_Data"""

data = pd.read_sql(query,cnxn)
#cnxn.commit()
#cnxn.close()

In [82]:
data['Accuracy'].value_counts()

True     973657
False    160807
Name: Accuracy, dtype: int64

In [51]:
df=pd.DataFrame()
df['Agent CAT Name']=data['Agent CAT Name'].unique()
df.to_csv('df.csv')

In [52]:
df

                                 Agent CAT Name
0                 CAT_PREPARED_FOOD,TEMP_HEATED
1               CAT_PREPACKAGED_FOOD_CONDIMENTS
2              CAT_PREPARED_DRINK,TEMP_UNHEATED
3        CAT_PREPARED_FOOD_PREPARED_SIDE_DISHES
4    CAT_SOFT_DRINK,CONTAINER_BOTTLED,TEMP_COLD
..                                          ...
186                                 CAT_POSTAGE
187                                 CAT_PROPANE
188                CAT_OTC_MEDICATION_ESTROGENS
189                                CAT_COSTUMES
190        CAT_JUICE,TRAIT_PCT_25TO49,TEMP_COLD

[191 rows x 1 columns]

In [73]:
gf=data[data['ML CAT Name'].isnull()]

In [74]:
gf

Empty DataFrame
Columns: [CICD Run Date, Date (BOT Sent Details to COE Team), UniqueUUID, store_uuid, item_uuid, Item, Description, establishment_type, ML CAT Name, ML Integer, ML Confidence Score, Agent CAT Name, Agent Integer, Accuracy, New ML Prediction, New ML Integer, New Accuracy, Module]
Index: []

In [42]:
gf.to_csv('gf.csv')

In [83]:
bf=data[data['Agent Integer'].isnull() & data['Agent CAT Name'].isnull()]

In [84]:
bf

,CICD Run Date,Date (BOT Sent Details to COE Team),UniqueUUID,store_uuid,item_uuid,Item,Description,establishment_type,ML CAT Name,ML Integer,ML Confidence Score,Agent CAT Name,Agent Integer,Accuracy,New ML Prediction,New ML Integer,New Accuracy,Module
5234,2022-09-05 18:56:00,2022-05-02 18:37:00,00e04333-5a1a-4ba5-8ef9-33853ecadaef:de9e550a-...,00e04333-5a1a-4ba5-8ef9-33853ecadaef,de9e550a-6632-4074-ab19-5a9276a8c5ea,Can of Soda,\\N,DEFAULT,"CAT_SOFT_DRINK,CONTAINER_BOTTLED,TEMP_COLD","112,11,3",0.51,None,None,False,None,None,None,Restaurants
11211,2022-01-09 01:30:00,2022-08-29 23:35:00,02bd32ff-c5a6-5b82-a0db-0fb2201e16b5:0ca94e83-...,02bd32ff-c5a6-5b82-a0db-0fb2201e16b5,0ca94e83-e7e2-522d-8fb6-db44fff1b4dd,Nature's Touch Egg,None,None,CAT_PREPACKAGED_FOOD_EGGS,728,0.15,None,None,False,None,None,None,Grocery
43175,2022-09-05 18:56:00,2022-05-02 18:37:00,0a7c98f1-3327-4624-8c87-2830a8afaf65:48e92ef1-...,0a7c98f1-3327-4624-8c87-2830a8afaf65,48e92ef1-73b1-57d8-9c1b-271f6113d1dc,Large Dr Pepper,\\N,DEFAULT,"CAT_PREPARED_DRINK,TEMP_UNHEATED","114,2",0.28,None,None,False,None,None,None,Restaurants
43179,2022-09-05 18:56:00,2022-05-02 18:37:00,0a7c98f1-3327-4624-8c87-2830a8afaf65:7a355b51-...,0a7c98f1-3327-4624-8c87-2830a8afaf65,7a355b51-201e-5366-91cb-4b745a80a834,Large Coca-ColaÂ®,\\N,DEFAULT,"CAT_PREPARED_DRINK,TEMP_UNHEATED","114,2",0.43,None,None,False,None,None,None,Restaurants
48892,2022-09-05 18:56:00,2022-05-02 18:37:00,0b25e70d-b860-570b-b39e-0ca9cae7f3cf:376d08b1-...,0b25e70d-b860-570b-b39e-0ca9cae7f3cf,376d08b1-9844-4df7-99cf-2310bbf1aeb0,Tempura Ice Cream,Fried ice cream.,DEFAULT,"CAT_PREPARED_FOOD,TEMP_HEATED","101,1",0.43,None,None,False,None,None,None,Restaurants
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065947,2022-05-08 05:03:00,2022-04-08 02:53:00,ee9abbdd-4a82-5d37-b6fe-f0e6cdc9169d:fe822e7f-...,ee9abbdd-4a82-5d37-b6fe-f0e6cdc9169d,fe822e7f-475e-5b65-8314-7d7e2d414cba,Milky Way Milk Chocolate Candy Bar Share Size,3.63 oz,CONVENIENCE,CAT_CONFECTIONARY,707,0.63,None,None,False,None,None,None,Grocery
1065950,2022-05-08 05:03:00,2022-04-08 02:53:00,ee9abbdd-4a82-5d37-b6fe-f0e6cdc9169d:fee74d59-...,ee9abbdd-4a82-5d37-b6fe-f0e6cdc9169d,fee74d59-0345-55f6-8319-f7f11caa56dd,VENOM Killer Taipan Energy Drink,16 Oz,CONVENIENCE,"CAT_FOOD_BY_WT_VOL,TEMP_UNHEATED","103,2",0.47,None,None,False,None,None,None,Grocery
1065951,2022-05-08 05:03:00,2022-04-08 02:53:00,ee9abbdd-4a82-5d37-b6fe-f0e6cdc9169d:ff8ece2f-...,ee9abbdd-4a82-5d37-b6fe-f0e6cdc9169d,ff8ece2f-583e-59a6-b436-d7fc5b123c9a,Paint Roller Candy,None,CONVENIENCE,"CAT_CANDY,TEMP_COLD","108,3",0.29,None,None,False,None,None,None,Grocery
1065952,2022-05-08 05:03:00,2022-04-08 02:53:00,ee9abbdd-4a82-5d37-b6fe-f0e6cdc9169d:ff91fde4-...,ee9abbdd-4a82-5d37-b6fe-f0e6cdc9169d,ff91fde4-eece-5f17-97c1-a3bd6fdcdd5d,Andes CrÃ¨me de Menthe Thin Mints,30 Oz,CONVENIENCE,CAT_CONFECTIONARY,707,0.44,None,None,False,None,None,None,Grocery
1087923,2022-09-05 18:56:00,2022-05-02 18:37:00,f34f5172-8fc9-59cf-a34c-7ddd16615b9e:113f4ba3-...,f34f5172-8fc9-59cf-a34c-7ddd16615b9e,113f4ba3-56c3-4f98-92b3-6d0326622c53,THE 11:11 MEAL,1 Korean ground meat roll \\n1 Pork Belly Stac...,DEFAULT,"CAT_PREPARED_FOOD,TEMP_HEATED","101,1",0.61,None,None,False,None,None,None,Restaurants

In [30]:
#bf.to_csv('bf.csv')

In [4]:
#df=pd.DataFrame()
#df['Agent CAT Name']=data['Agent CAT Name'].unique()

In [5]:
#df.to_csv('df.csv')

In [3]:
#data.to_csv("taxml_validation_tablecompletedata_12_5_2022.csv")

In [31]:
mapping_data=pd.read_csv('bf.csv')
mapping_data.shape

(2415, 19)

In [34]:
mapping_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2415 entries, 0 to 2414
Data columns (total 19 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Unnamed: 0                           2415 non-null   int64
 1   CICD Run Date                        2415 non-null   object
 2   Date (BOT Sent Details to COE Team)  2415 non-null   object
 3   UniqueUUID                           2415 non-null   object
 4   store_uuid                           2415 non-null   object
 5   item_uuid                            2415 non-null   object
 6   Item                                 2413 non-null   object
 7   Description                          2163 non-null   object
 8   establishment_type                   2411 non-null   object
 9   ML CAT Name                          2415 non-null   object
 10  ML Integer                           2415 non-null   object
 11  ML Confidence Score                  2415 non-null   float64
 12  Agent CAT Name                       1683 non-null   object
 13  Agent Integer                        1690 non-null   object
 14  Accuracy                             2415 non-null   bool
 15  New ML Prediction                    0 non-null      float64
 16  New ML Integer                       0 non-null      float64
 17  New Accuracy                         0 non-null      float64
 18  Module                               2415 non-null   object
dtypes: bool(1), float64(4), int64(1), object(13)
memory usage: 342.1+ KB

In [33]:
#df=pd.DataFrame()
#df['Agent CAT Name']=data['Agent CAT Name'].unique()
#df.to_csv('df.csv')
#mapping_data=pd.read_csv('mapping.csv')
#cat_dict = dict(zip(mapping_data['Agent CAT Name'], mapping_data['Updated CAT Name']))
#int_dict = dict(zip(mapping_data['Agent CAT Name'], mapping_data['Updated Integer']))
#data["Updated CAT Name"] = data["Agent CAT Name"].map(cat_dict)
#data["Updated Integer"] = data["Agent CAT Name"].map(int_dict)
#data['Updated CAT Name'].fillna(value=data['Agent CAT Name'], inplace=True)
#data['Updated Integer'].fillna(value=data['Agent Integer'], inplace=True)

In [75]:
#data["ML CAT Name"] = data["ML CAT Name"].map(cat_dict)
#data["ML Integer"] = data["ML CAT Name"].map(int_dict)
#data['ML CAT Name'].fillna(value=data['Agent CAT Name'], inplace=True)
#data['ML Integer'].fillna(value=data['Agent Integer'], inplace=True)

In [77]:
#data[data['Accuracy']==False]
106,107,1

,CICD Run Date,Date (BOT Sent Details to COE Team),UniqueUUID,store_uuid,item_uuid,Item,Description,establishment_type,ML CAT Name,ML Integer,ML Confidence Score,Agent CAT Name,Agent Integer,Accuracy,New ML Prediction,New ML Integer,New Accuracy,Module,Updated CAT Name,Updated Integer
2,2022-05-26 19:54:00,2022-05-19 19:08:00,0001a851-7ca3-484f-b3e6-75899dd18207:2f7fc8d6-...,0001a851-7ca3-484f-b3e6-75899dd18207,2f7fc8d6-8167-5521-b3ee-7e19281e6d60,Get Saucy,Our sauce secret is out Creamy Ranch Dressing ...,DEFAULT,"CAT_PREPARED_FOOD,TEMP_HEATED","101,1",0.70,CAT_PREPACKAGED_FOOD_CONDIMENTS,740,False,None,None,None,Restaurants,CAT_PREPACKAGED_FOOD_CONDIMENTS,740
9,2022-05-26 19:54:00,2022-05-19 19:08:00,0001a851-7ca3-484f-b3e6-75899dd18207:d68405ba-...,0001a851-7ca3-484f-b3e6-75899dd18207,d68405ba-6ba6-5427-8833-0552c00627f3,Garlic Fries,Thick cut and fried to perfection with garlic ...,DEFAULT,"CAT_PREPARED_FOOD,TEMP_HEATED","101,1",0.50,CAT_PREPARED_FOOD_PREPARED_SIDE_DISHES,751,False,None,None,None,Restaurants,CAT_PREPARED_FOOD_PREPARED_SIDE_DISHES,751
10,2022-05-26 19:54:00,2022-05-19 19:08:00,0001a851-7ca3-484f-b3e6-75899dd18207:dbced002-...,0001a851-7ca3-484f-b3e6-75899dd18207,dbced002-ad04-59dd-b4d3-ac9e742c8a42,Steak Fries,Thick cut and fried to perfection with Red s O...,DEFAULT,"CAT_PREPARED_FOOD,TEMP_HEATED","101,1",0.70,CAT_PREPARED_FOOD_PREPARED_SIDE_DISHES,751,False,None,None,None,Restaurants,CAT_PREPARED_FOOD_PREPARED_SIDE_DISHES,751
205,2022-09-29 07:20:00,2022-06-30 07:58:00,00120bc6-7799-5266-8b9e-cdb4967e1001:0f532a6f-...,00120bc6-7799-5266-8b9e-cdb4967e1001,0f532a6f-eb83-5150-bace-800bb179102f,Broccoli,Tender broccoli florets steamed to order.,DEFAULT,"CAT_PREPARED_FOOD,TEMP_HEATED","101,1",0.80,CAT_PREPARED_FOOD_PREPARED_SIDE_DISHES,751,False,None,None,None,Restaurants,CAT_PREPARED_FOOD_PREPARED_SIDE_DISHES,751
209,2022-09-29 07:20:00,2022-06-30 07:58:00,00120bc6-7799-5266-8b9e-cdb4967e1001:1d682ad4-...,00120bc6-7799-5266-8b9e-cdb4967e1001,1d682ad4-ef58-583f-ab34-b69eee5d22b4,Baked Potato,A generous sized potato cooked to fluffy perfe...,DEFAULT,"CAT_PREPARED_FOOD,TEMP_HEATED","101,1",0.70,CAT_PREPARED_FOOD_PREPARED_SIDE_DISHES,751,False,None,None,None,Restaurants,CAT_PREPARED_FOOD_PREPARED_SIDE_DISHES,751
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1134425,2022-02-22 12:59:00,2022-02-21 02:15:00,fff1d6b3-17b1-58cb-9d38-e4cdd3aa0e50:e4426774-...,fff1d6b3-17b1-58cb-9d38-e4cdd3aa0e50,e4426774-ddec-4023-89d3-12937202b80f,Salsa of Mild Red Salsa,None,DEFAULT,"CAT_PREPARED_DRINK,TEMP_HEATED","114,1",0.60,CAT_PREPACKAGED_FOOD_CONDIMENTS,740,False,None,None,None,Grocery,CAT_PREPACKAGED_FOOD_CONDIMENTS,740
1134429,2022-02-22 12:59:00,2022-02-21 02:15:00,fff1d6b3-17b1-58cb-9d38-e4cdd3aa0e50:fcb7fc3f-...,fff1d6b3-17b1-58cb-9d38-e4cdd3aa0e50,fcb7fc3f-3255-4357-8e5b-69d11b459471,Side of Avocado Salsa Verde,Green avocado salsa,DEFAULT,"CAT_PREPARED_FOOD,TEMP_HEATED","101,1",0.60,CAT_PREPARED_FOOD_PREPARED_SIDE_DISHES,751,False,None,None,None,Grocery,CAT_PREPARED_FOOD_PREPARED_SIDE_DISHES,751
1134447,2022-07-28 08:39:00,2022-07-21 05:03:00,fffa3d89-bdc1-51b3-a588-f2282a88baa3:0268287a-...,fffa3d89-bdc1-51b3-a588-f2282a88baa3,0268287a-dad4-4dc6-a6db-79139866aa64,Ice Cream (Cone),None,GROCERY,"CAT_PREPACKAGED_FOOD,CAT_ICECREAM,TEMP_HEATED","106,105,1",0.65,"CAT_PREPACKAGED_FOOD,CAT_ICECREAM,TEMP_COLD","106,105,1",False,None,None,None,Grocery,"CAT_PREPACKAGED_FOOD,CAT_ICECREAM,TEMP_COLD","106,105,1"
1134455,2022-07-28 08:39:00,2022-07-21 05:03:00,fffa3d89-bdc1-51b3-a588-f2282a88baa3:aa935861-...,fffa3d89-bdc1-51b3-a588-f2282a88baa3,aa935861-37a7-4173-8cd9-c5245da1f519,Ice Cream (Cup),None,GROCERY,"CAT_PREPACKAGED_FOOD,CAT_ICECREAM,TEMP_HEATED","106,105,1",0.56,"CAT_PREPACKAGED_FOOD,CAT_ICECREAM,TEMP_COLD","106,105,1",False,None,None,None,Grocery,"CAT_PREPACKAGED_FOOD,CAT_ICECREAM,TEMP_COLD","106,105,1"
1134458,2022-09-09 01:18:00,2022-08-25 19:42:00,fffac49b-4f10-449c-8e2c-7d66166a1384:71134b9f-...,fffac49b-4f10-449c-8e2c-7d66166a1384,71134b9f-0e72-505d-986c-3922c25d0d3b,Pineapple Juice,None,DEFAULT,"CAT_JUICE,TRAIT_PCT_100,TEMP_HEATED","110,51,1",0.75,"CAT_PREPARED_DRINK,TEMP_HEATED","114,1",False,None,None,None,Restaurants,"CAT_PREPARED_DRINK,TEMP_UNHEATED","114,2"

In [38]:
for index, row in mapping_data.iterrows():
    uuid = row["UniqueUUID"]
    updatedcatname = row["ML CAT Name"]
    updatedinetger = row["ML Integer"]
    updatedconf = row["ML Confidence Score"]
    query1 = f""" UPDATE TaxML_Validation_Data SET [ML CAT Name] = '{updatedcatname}', [ML Integer] = '{updatedinetger}', [ML Confidence Score] = '{updatedconf}'
                Where [UniqueUUID] = '{uuid}' """
    cursor.execute(query1)
    cnxn.commit()

In [2]:
agentcatname = '-2146826265'
updatedcatname = ' '
updatedinetger = ' '
query1 = f""" UPDATE TaxML_Validation_Data SET [Agent CAT Name] = NULL, [Agent Integer] =  NULL
            Where [Agent CAT Name] = '{updatedinetger}' """
cursor.execute(query1)
cnxn.commit()

In [66]:
#agentcatname = ' '
updatedinetger = ' '
query1 = f""" UPDATE TaxML_Validation_Data SET  [Agent Integer] = NULL
            Where [Agent CAT Name] is null """
cursor.execute(query1)
cnxn.commit()

In [43]:
#agentcatname = '746'
updatedcatname = '-2146826265'
#updatedinetger = '746'
query1 = f""" UPDATE TaxML_Validation_Data SET [ML Confidence Score] = '{updatedcatname}'
            Where [ML Confidence Score] is null """
cursor.execute(query1)
cnxn.commit()

In [75]:
#for index, row in data.iterrows():
query3 = f"""UPDATE TaxML_Validation_Data 
            SET [Accuracy] = 0 """
cursor.execute(query3)
cnxn.commit()

In [79]:
#for index, row in data.iterrows():
query3 = f"""UPDATE TaxML_Validation_Data 
            SET [Accuracy] = 1 
            Where [ML CAT Name] = [Agent CAT Name]"""
cursor.execute(query3)
cnxn.commit()

In [85]:
query4 = f"""SELECT *, ROUND(CAST(e.predicted_true_count AS DECIMAL(16,2)) / e.total_volume,2) AS accuracy
                FROM (SELECT
                    [Establishment_type],[ML CAT Name],[Agent CAT Name], [Accuracy],
                    COUNT(CASE WHEN [Agent CAT Name] IS NOT NULL THEN [Agent CAT Name] END) AS total_volume,
                    COUNT(CASE WHEN [ML CAT Name]=[Agent CAT Name] THEN [Agent CAT Name] END) AS predicted_true_count
                FROM TaxML_Validation_Data
                GROUP BY [Establishment_type],[ML CAT Name],[Agent CAT Name], [Accuracy]) AS e
                WHERE e.predicted_true_count >= 1
                ORDER BY e.predicted_true_count DESC """
data_byET = pd.read_sql(query4,cnxn)
#cnxn.commit()

In [86]:
data_byET.to_csv("data_byET.csv")

In [25]:
data_updated = pd.read_sql(query,cnxn)
#cnxn.close()
data_updated.head()

,CICD Run Date,Date (BOT Sent Details to COE Team),UniqueUUID,store_uuid,item_uuid,Item,Description,establishment_type,ML CAT Name,ML Integer,ML Confidence Score,Agent CAT Name,Agent Integer,Accuracy,New ML Prediction,New ML Integer,New Accuracy,Module
0,2022-08-09 10:36:00,2022-06-30 11:11:00,000168cb-e79b-4299-af44-4f86e36a8464:c17291c5-...,000168cb-e79b-4299-af44-4f86e36a8464,c17291c5-83d2-5155-85d0-305e41695b95,Egg White & Veggie Omelet Bites,"Cage-free eggs mixed with spinach, tomatoes an...",DEFAULT,"CAT_PREPARED_FOOD,TEMP_HEATED","101,1",0.9,"CAT_PREPARED_FOOD,TEMP_HEATED","101,1",True,None,None,None,Restaurant
1,2022-05-26 19:54:00,2022-05-19 19:08:00,0001a851-7ca3-484f-b3e6-75899dd18207:1b0bb2ba-...,0001a851-7ca3-484f-b3e6-75899dd18207,1b0bb2ba-99c3-574f-b203-e9b3388d5184,Ensenada Chicken Platter,One or two ancho-grilled chicken breasts house...,DEFAULT,"CAT_PREPARED_FOOD,TEMP_HEATED","101,1",1.0,"CAT_PREPARED_FOOD,TEMP_HEATED","101,1",True,None,None,None,Restaurants
2,2022-05-26 19:54:00,2022-05-19 19:08:00,0001a851-7ca3-484f-b3e6-75899dd18207:2f7fc8d6-...,0001a851-7ca3-484f-b3e6-75899dd18207,2f7fc8d6-8167-5521-b3ee-7e19281e6d60,Get Saucy,Our sauce secret is out Creamy Ranch Dressing ...,DEFAULT,"CAT_PREPARED_FOOD,TEMP_HEATED","101,1",0.7,CAT_PREPACKAGED_FOOD_CONDIMENTS,740,True,None,None,None,Restaurants
3,2022-05-26 19:54:00,2022-05-19 19:08:00,0001a851-7ca3-484f-b3e6-75899dd18207:3bc15321-...,0001a851-7ca3-484f-b3e6-75899dd18207,3bc15321-d86f-51a9-a12b-438a8c69a591,Donatos 10 Pizza,10 Donatos famous crispy thin crust loaded Edg...,DEFAULT,"CAT_PREPARED_FOOD,TEMP_HEATED","101,1",0.6,"CAT_PREPARED_FOOD,TEMP_HEATED","101,1",True,None,None,None,Restaurants
4,2022-05-26 19:54:00,2022-05-19 19:08:00,0001a851-7ca3-484f-b3e6-75899dd18207:44c840cc-...,0001a851-7ca3-484f-b3e6-75899dd18207,44c840cc-3544-55b6-969c-56902c07899a,Donatos 7 Pizza,Loaded Edge to Edge with our heritage recipe P...,DEFAULT,"CAT_PREPARED_FOOD,TEMP_HEATED","101,1",0.6,"CAT_PREPARED_FOOD,TEMP_HEATED","101,1",True,None,None,None,Restaurants

In [7]:
agentcatname_list = list(mapping_data['Agent CAT Name'])
#data_updated.loc[data_updated['Agent CAT Name'] == "Antidiarrheals"]
data_updated.loc[data_updated['Agent CAT Name'].isin(agentcatname_list)]

Empty DataFrame
Columns: [CICD Run Date, Date (BOT Sent Details to COE Team), UniqueUUID, store_uuid, item_uuid, Item, Description, establishment_type, ML CAT Name, ML Integer, ML Confidence Score, Agent CAT Name, Agent Integer, Accuracy, New ML Prediction, New ML Integer, New Accuracy, Module]
Index: []

In [11]:
agentcatname_list = list(mapping_data['Agent CAT Name'])
#data_updated.loc[data_updated['Agent CAT Name'] == "Antidiarrheals"]
data_updated.loc[data_updated['ML CAT Name'].isin(agentcatname_list)]

Empty DataFrame
Columns: [CICD Run Date, Date (BOT Sent Details to COE Team), UniqueUUID, store_uuid, item_uuid, Item, Description, establishment_type, ML CAT Name, ML Integer, ML Confidence Score, Agent CAT Name, Agent Integer, Accuracy, New ML Prediction, New ML Integer, New Accuracy, Module]
Index: []

In [21]:
count = data_updated.nunique()
count

CICD Run Date                              227
Date (BOT Sent Details to COE Team)       2908
UniqueUUID                             1134464
store_uuid                               31308
item_uuid                              1104264
Item                                    354568
Description                             137909
establishment_type                          12
ML CAT Name                                260
ML Integer                                 277
ML Confidence Score                       1197
Agent CAT Name                             195
Agent Integer                              220
Accuracy                                     2
New ML Prediction                            1
New ML Integer                               1
New Accuracy                                 1
Module                                       4
dtype: int64

In [23]:
data['Accuracy'].value_counts()

True     929429
False    205035
Name: Accuracy, dtype: int64

In [26]:
data_updated['Accuracy'].value_counts()

True     1131558
False       2906
Name: Accuracy, dtype: int64